/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StyleImport } from './routes/style'
import { Route as WizardRouteImport } from './routes/wizard.route'
import { Route as IndexImport } from './routes/index'
import { Route as WizardIndexImport } from './routes/wizard.index'
import { Route as WizardSummaryImport } from './routes/wizard.summary'
import { Route as WizardPersonalImport } from './routes/wizard.personal'

// Create/Update Routes

const StyleRoute = StyleImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => rootRoute,
} as any)

const WizardRouteRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WizardIndexRoute = WizardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WizardRouteRoute,
} as any)

const WizardSummaryRoute = WizardSummaryImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => WizardRouteRoute,
} as any)

const WizardPersonalRoute = WizardPersonalImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => WizardRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRoute
    }
    '/style': {
      id: '/style'
      path: '/style'
      fullPath: '/style'
      preLoaderRoute: typeof StyleImport
      parentRoute: typeof rootRoute
    }
    '/wizard/personal': {
      id: '/wizard/personal'
      path: '/personal'
      fullPath: '/wizard/personal'
      preLoaderRoute: typeof WizardPersonalImport
      parentRoute: typeof WizardRouteImport
    }
    '/wizard/summary': {
      id: '/wizard/summary'
      path: '/summary'
      fullPath: '/wizard/summary'
      preLoaderRoute: typeof WizardSummaryImport
      parentRoute: typeof WizardRouteImport
    }
    '/wizard/': {
      id: '/wizard/'
      path: '/'
      fullPath: '/wizard/'
      preLoaderRoute: typeof WizardIndexImport
      parentRoute: typeof WizardRouteImport
    }
  }
}

// Create and export the route tree

interface WizardRouteRouteChildren {
  WizardPersonalRoute: typeof WizardPersonalRoute
  WizardSummaryRoute: typeof WizardSummaryRoute
  WizardIndexRoute: typeof WizardIndexRoute
}

const WizardRouteRouteChildren: WizardRouteRouteChildren = {
  WizardPersonalRoute: WizardPersonalRoute,
  WizardSummaryRoute: WizardSummaryRoute,
  WizardIndexRoute: WizardIndexRoute,
}

const WizardRouteRouteWithChildren = WizardRouteRoute._addFileChildren(
  WizardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wizard': typeof WizardRouteRouteWithChildren
  '/style': typeof StyleRoute
  '/wizard/personal': typeof WizardPersonalRoute
  '/wizard/summary': typeof WizardSummaryRoute
  '/wizard/': typeof WizardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/style': typeof StyleRoute
  '/wizard/personal': typeof WizardPersonalRoute
  '/wizard/summary': typeof WizardSummaryRoute
  '/wizard': typeof WizardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/wizard': typeof WizardRouteRouteWithChildren
  '/style': typeof StyleRoute
  '/wizard/personal': typeof WizardPersonalRoute
  '/wizard/summary': typeof WizardSummaryRoute
  '/wizard/': typeof WizardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/wizard'
    | '/style'
    | '/wizard/personal'
    | '/wizard/summary'
    | '/wizard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/style' | '/wizard/personal' | '/wizard/summary' | '/wizard'
  id:
    | '__root__'
    | '/'
    | '/wizard'
    | '/style'
    | '/wizard/personal'
    | '/wizard/summary'
    | '/wizard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WizardRouteRoute: typeof WizardRouteRouteWithChildren
  StyleRoute: typeof StyleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WizardRouteRoute: WizardRouteRouteWithChildren,
  StyleRoute: StyleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/wizard",
        "/style"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/wizard": {
      "filePath": "wizard.route.tsx",
      "children": [
        "/wizard/personal",
        "/wizard/summary",
        "/wizard/"
      ]
    },
    "/style": {
      "filePath": "style.tsx"
    },
    "/wizard/personal": {
      "filePath": "wizard.personal.tsx",
      "parent": "/wizard"
    },
    "/wizard/summary": {
      "filePath": "wizard.summary.tsx",
      "parent": "/wizard"
    },
    "/wizard/": {
      "filePath": "wizard.index.tsx",
      "parent": "/wizard"
    }
  }
}
ROUTE_MANIFEST_END */
